
(function () {
  function boot() {
    if (!window.CMS || !window.CMS.createClass || !window.CMS.h) return;
    var CMS = window.CMS, h = CMS.h, createClass = CMS.createClass;
    function getValue(entry, field, fallback) { var value = entry && entry.getIn ? entry.getIn(["data", field]) : null; return (value === undefined || value === null || value === "") ? (fallback || "") : value; }
    function listToArray(value) { if (!value) return []; if (typeof value.toJS === "function") return value.toJS(); return Array.isArray(value) ? value : []; }
    function photos(entry, fieldName) { return listToArray(entry.getIn(["data", fieldName])).map(function (item) { if (!item) return ""; if (typeof item === "string") return item; return item.image || item.src || item.url || ""; }).filter(Boolean); }
    function paragraphs(entry) { return String(getValue(entry, "body", "")).split(/\n{2,}/).filter(Boolean); }
    function formatDate(value) { if (!value) return "Date will show here"; var d = new Date(value); if (isNaN(d.getTime())) return String(value); return d.toLocaleDateString("en-NZ", { day: "numeric", month: "long", year: "numeric" }); }
    var pageStyle = { fontFamily: "Georgia, serif", background: "#f7f3ee", padding: "24px", color: "#2f1c14" }, cardStyle = { background: "#fff", border: "1px solid #eadfce", borderRadius: "22px", overflow: "hidden", boxShadow: "0 10px 30px rgba(40,24,18,.08)" };
    var EventPreview = createClass({ render: function () { var entry = this.props.entry, title = getValue(entry, "title", "Event title preview"), desc = getValue(entry, "description", "This text appears in the event card and modal."), meta = [getValue(entry, "category", "Photo Gallery"), getValue(entry, "date_display", formatDate(getValue(entry, "date", ""))), getValue(entry, "time", "")].filter(Boolean).join(" · "), flyer = getValue(entry, "flyer", ""), imgs = photos(entry, "photos"), cover = imgs[0] || flyer; return h("div", { style: pageStyle }, [ h("h2", { style: { marginTop: 0 } }, "How it will look on the Events page"), h("div", { style: Object.assign({ maxWidth: "360px" }, cardStyle) }, [ cover ? h("img", { src: cover, style: { width: "100%", height: "240px", objectFit: "cover", display: "block" } }) : null, h("div", { style: { padding: "20px" } }, [ h("div", { style: { color: "#c9a961", textTransform: "uppercase", fontSize: "12px", fontWeight: "700", letterSpacing: "0.12em", marginBottom: "10px" } }, getValue(entry, "category", "Event")), h("h3", { style: { margin: "0 0 10px", fontSize: "34px", lineHeight: "1.05" } }, title), meta ? h("p", { style: { margin: "0 0 12px", color: "#6a5b52" } }, meta) : null, h("p", { style: { margin: 0, color: "#6a5b52" } }, desc), h("p", { style: { margin: "14px 0 0", color: "#a12f27", fontWeight: "700" } }, (imgs.length || getValue(entry, "display_mode", "gallery") === "gallery") ? "Open gallery →" : "Open event →") ]) ]), h("h2", { style: { margin: "34px 0 14px" } }, "Popup preview"), h("div", { style: Object.assign({ maxWidth: "960px", background: "#fbf8f4" }, cardStyle) }, [ h("div", { style: { padding: "20px 24px", borderBottom: "1px solid #eadfce" } }, [ h("h3", { style: { margin: 0, fontSize: "42px" } }, title) ]), h("div", { style: { display: "grid", gridTemplateColumns: "1.05fr .95fr" } }, [ h("div", { style: { background: "#111", minHeight: "420px", display: "flex", alignItems: "center", justifyContent: "center", padding: "16px" } }, [ cover ? h("img", { src: cover, style: { maxWidth: "100%", maxHeight: "100%", objectFit: "contain" } }) : null ]), h("div", { style: { padding: "24px" } }, [ h("div", { style: { display: "inline-block", padding: "8px 12px", borderRadius: "999px", background: "#f1e7da", fontWeight: "700", marginBottom: "14px" } }, (imgs.length || 1) + " image" + ((imgs.length || 1) > 1 ? "s" : "")), meta ? h("p", { style: { color: "#6a5b52", marginTop: 0 } }, meta) : null, h("p", { style: { color: "#6a5b52" } }, desc) ]) ]) ]) ]); } });
    var NewsPreview = createClass({ render: function () { var entry = this.props.entry, title = getValue(entry, "title", "News title preview"), excerpt = getValue(entry, "excerpt", "A short summary shown on the homepage and news page."), cover = getValue(entry, "cover_image", ""), imgs = photos(entry, "photos"), paras = paragraphs(entry), dateText = formatDate(getValue(entry, "publish_date", "")); return h("div", { style: pageStyle }, [ h("h2", { style: { marginTop: 0 } }, "Homepage News card preview"), h("div", { style: Object.assign({ maxWidth: "360px" }, cardStyle) }, [ cover ? h("img", { src: cover, style: { width: "100%", height: "240px", objectFit: "cover", display: "block" } }) : null, h("div", { style: { padding: "20px" } }, [ h("div", { style: { color: "#c9a961", textTransform: "uppercase", fontSize: "12px", fontWeight: "700", letterSpacing: "0.12em", marginBottom: "10px" } }, dateText), h("h3", { style: { margin: "0 0 10px", fontSize: "34px", lineHeight: "1.05" } }, title), h("p", { style: { margin: 0, color: "#6a5b52" } }, excerpt), h("p", { style: { margin: "14px 0 0", color: "#a12f27", fontWeight: "700" } }, "Read article →") ]) ]), h("h2", { style: { margin: "34px 0 14px" } }, "News page article preview"), h("div", { style: Object.assign({ maxWidth: "960px" }, cardStyle) }, [ cover ? h("img", { src: cover, style: { width: "100%", height: "340px", objectFit: "cover", display: "block" } }) : null, h("div", { style: { padding: "24px" } }, [ h("div", { style: { color: "#c9a961", textTransform: "uppercase", fontSize: "12px", fontWeight: "700", letterSpacing: "0.12em", marginBottom: "10px" } }, dateText), h("h1", { style: { margin: "0 0 14px", fontSize: "44px", lineHeight: "1.05" } }, title), h("p", { style: { color: "#6a5b52" } }, excerpt), (paras.length ? paras : ["Article body goes here."]).map(function (p, i) { return h("p", { key: i, style: { color: "#6a5b52" } }, p); }), imgs.length ? h("div", { style: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "12px", marginTop: "20px" } }, imgs.map(function (src, i) { return h("img", { key: i, src: src, style: { width: "100%", height: "160px", objectFit: "cover", borderRadius: "14px" } }); })) : null ]) ]) ]); } });
    CMS.registerPreviewTemplate("events", EventPreview); CMS.registerPreviewTemplate("news", NewsPreview);
  }
  if (window.CMS) boot(); else window.addEventListener("load", boot);
})();
